name: food_delivery
description: "A new Flutter project for food delivery."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6 # Vérifiez la dernière version disponible sur pub.dev
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  http: ^0.13.6
  geolocator: ^9.0.2
  simple_animations: ^3.1.1
  rive: ^0.10.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7 # Version actuelle (remplacez si une version plus récente est disponible)
  carousel_slider: ^4.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Correctly formatted assets section
  assets:
    - assets/images/burger.jpeg
    - assets/images/chawarma.jpeg
    - assets/images/logo1.jpeg
    - assets/images/pizza.jpeg
